{"uuid": "c08a0905-4523-4a59-bbb4-3774993544d0", "children": ["bf4e729a-ef84-473d-b48f-cc0eb827f06e"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=122.0.6261.128)\nStacktrace:\n\tGetHandleVerifier [0x003D8D03+51395]\n\t(No symbol) [0x00345F61]\n\t(No symbol) [0x001FE13A]\n\t(No symbol) [0x001E25F2]\n\t(No symbol) [0x00259B2B]\n\t(No symbol) [0x00269E66]\n\t(No symbol) [0x00253C26]\n\t(No symbol) [0x0022C629]\n\t(No symbol) [0x0022D40D]\n\tGetHandleVerifier [0x007568D3+3712147]\n\tGetHandleVerifier [0x00795CBA+3971194]\n\tGetHandleVerifier [0x00790FA8+3951464]\n\tGetHandleVerifier [0x00489D09+776393]\n\t(No symbol) [0x00351734]\n\t(No symbol) [0x0034C618]\n\t(No symbol) [0x0034C7C9]\n\t(No symbol) [0x0033DDF0]\n\tBaseThreadInitThunk [0x769E7BA9+25]\n\tRtlInitializeExceptionChain [0x7750BD2B+107]\n\tRtlClearBits [0x7750BCAF+191]\n\n", "trace": "  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\Scale Selenium Project\\Consumer_Side_Appointment\\Consumer_SIde_Appointment_Reschedule_test.py\", line 34, in login\n    driver.maximize_window()\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Archana\\PycharmProjects\\JaldeeUI.Automation\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711001370023, "stop": 1711001394921}], "start": 1711001370023, "stop": 1711001403500}